import { createHash, createHmac, timingSafeEqual } from 'crypto';

// Telegram Login Widget's own signature scheme, not an API call — Telegram
// signs the data client-side using our bot's token as a shared secret, and
// we verify it here locally. No network round-trip to Telegram is needed
// (or possible) to validate a login.
export interface TelegramAuthData {
  id: string; // kept as string throughout — this becomes User.telegramId
  first_name: string;
  last_name?: string;
  username?: string;
  photo_url?: string;
  auth_date: number;
}

// Generous enough for a real login (network hiccup, a slow client) but not
// unbounded — an old, once-legitimately-signed payload (e.g. leaked via a
// referrer header or a shared screenshot) shouldn't be replayable forever.
const AUTH_MAX_AGE_S = 600; // 10 хвилин
// Widget's auth_date is generated by Telegram's own servers, verified here
// on ours — different infrastructure, same clock-skew reasoning already
// applied to the session cookie in middleware.ts. Without this, a login
// could spuriously fail if Telegram's clock is even 1s ahead of ours.
const CLOCK_SKEW_TOLERANCE_S = 5;

export function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
}

// Returns the verified fields on success, or null if the signature is
// invalid, missing required fields, or the payload is stale/tampered.
// Never throws on malformed input — this is client-supplied data.
export function verifyTelegramAuth(data: Record<string, unknown>, botToken: string): TelegramAuthData | null {
  const { hash, ...rest } = data;
  if (typeof hash !== 'string' || !hash) return null;

  // Data-check-string per Telegram's spec: every field except hash, sorted
  // alphabetically by key, joined as "key=value" with a newline separator.
  const checkString = Object.keys(rest)
    .filter(k => rest[k] !== undefined && rest[k] !== null && rest[k] !== '')
    .sort()
    .map(k => `${k}=${rest[k]}`)
    .join('\n');

  const secretKey = createHash('sha256').update(botToken).digest();
  const computedHash = createHmac('sha256', secretKey).update(checkString).digest('hex');
  if (!safeEqual(computedHash, hash)) return null;

  const authDate = Number(rest.auth_date);
  if (!Number.isFinite(authDate)) return null;
  const age = Date.now() / 1000 - authDate;
  if (age < -CLOCK_SKEW_TOLERANCE_S || age > AUTH_MAX_AGE_S) return null; // stale, or issued implausibly far in the future

  const rawId = rest.id;
  if (rawId === undefined || rawId === null || String(rawId).trim() === '') return null;
  const firstName = rest.first_name;
  if (typeof firstName !== 'string' || !firstName) return null;

  return {
    id: String(rawId),
    first_name: firstName,
    last_name: typeof rest.last_name === 'string' ? rest.last_name : undefined,
    username: typeof rest.username === 'string' ? rest.username : undefined,
    photo_url: typeof rest.photo_url === 'string' ? rest.photo_url : undefined,
    auth_date: authDate,
  };
}

const PENDING_REGISTRATION_MAX_AGE_MS = 10 * 60 * 1000; // 10 хвилин на завершення форми

// Signs the verified Telegram identity so it can round-trip through the
// browser (POST /api/auth/telegram returns this, the registration-complete
// step sends it back) without trusting the client to not tamper with it.
// Without this, a first-time-login response handing raw telegramId/username
// back to the frontend would let anyone POST an arbitrary telegramId
// straight to the register endpoint, skipping HMAC verification entirely —
// claiming someone else's Telegram identity for their own account.
export function signPendingRegistration(secret: string, data: TelegramAuthData): string {
  const payload = Buffer.from(JSON.stringify(data)).toString('base64url');
  const issuedAt = Date.now();
  const sig = createHmac('sha256', secret).update(`pending-registration:${payload}:${issuedAt}`).digest('hex');
  return `${payload}.${issuedAt}.${sig}`;
}

export function verifyPendingRegistration(secret: string, token: string): TelegramAuthData | null {
  const parts = token.split('.');
  if (parts.length !== 3) return null;
  const [payload, issuedAtStr, sig] = parts;
  const issuedAt = Number(issuedAtStr);
  if (!Number.isFinite(issuedAt)) return null;
  const age = Date.now() - issuedAt;
  if (age < -CLOCK_SKEW_TOLERANCE_S * 1000 || age > PENDING_REGISTRATION_MAX_AGE_MS) return null;
  const expected = createHmac('sha256', secret).update(`pending-registration:${payload}:${issuedAt}`).digest('hex');
  if (!safeEqual(sig, expected)) return null;
  try {
    return JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}
